export const PRICE = 250;

export const products = [
  { slug: "magot", name: "Магот" },
  {
    slug: "dzhunior",
    name: "Джуниор",
    items: [
      { name: "Белый (J01)", image: "/J01.jpg" },
      { name: "Чёрный (J02)", image: "/J02.jpg" },
      { name: "Красный (J03)", image: "/J03.jpg" },
      { name: "Синий (J04)", image: "/J04.jpg" },
      { name: "Светло-зелёный (J05)", image: "/J05.jpg" },
      { name: "Прозрачный глиттер (J06)" },
      { name: "Розовый (J07)", image: "/J07.jpg" },
      { name: "Коричневый (J08)", image: "/J08.jpg" },
      { name: "Прозрачный (J09)", image: "/J09.jpg" },
      { name: "Фиолетовый (J10)", image: "/J10.jpg" },
      { name: "Оранжевый (J11)", image: "/J11.jpg" },
      { name: "Тёмно-розовый (J12)", image: "/J12.jpg" },
      { name: "Зелёный (J13)", image: "/J13.jpg" },
      { name: "Оранжево-синий (J14)", image: "/J14.jpg" },
      { name: "Жёлто-зелёный (J15)", image: "/J15.jpg" },
      { name: "Оранжево-жёлтый (J16)", image: "/J16.jpg" },
      { name: "Бело-зелёный (J17)", image: "/J17.jpg" },
      { name: "Чёрно-белый (J18)" },
      { name: "Фиолетово-чёрный (J19)" },
      { name: "Бело-розовый (J20)" },
      { name: "Чёрно-оранжевый (J21)" },
      { name: "Бело-оранжевый (J22)", image: "/J22.jpg" },
      { name: "Жёлто-синий (J23)", image: "/J23.jpg" },
      { name: "Чёрно-зелёный глиттер (J24)", image: "/J24.jpg" },
      { name: "Жёлто-белый (J25)", image: "/J25.jpg" },
      { name: "Красно-белый (J26)", image: "/J26.jpg" },
      { name: "Оранжево-розовый (J27)", image: "/J27.jpg" },
      { name: "Розово-зелёный (J28)", image: "/J28.jpg" },
      { name: "Бело-оранжевый (J29)", image: "/J29.jpg" },
      { name: "Коричнево-белый (J30)", image: "/J30.jpg" },
    ],
  },
  { slug: "plamp", name: "Пламп" },
  { slug: "bobr", name: "Бобриный хвост" },
];
